# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31a8964fe5d8759ed2a16bfb102684d4bf0d21913cb0ca35aa040f4656d33ca8b22eedaf728241da671fc100b3c32c47fbfb97a4e168a0ee7902919797382a26

test:
  secret_key_base: 2a4986b06cc81450c19870fb54ef596f3af6020ed16d0a5b85e1240b581e4960037367d9b148de1b33c00bbafd600f7ad1b20dee5afcd44295ad4ff842321c74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
